name: Files Browser Frontend

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  container-image:
    uses: ionutbalutoiu/gha-utils/.github/workflows/docker-buildx.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      image_name: files-browser-frontend
      context: .
      platforms: linux/amd64, linux/arm64
    secrets: inherit
